// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkxCpL8Rxuk4dHegVoUE7l2I-3d1FIVHY',
    appId: '1:713866295722:web:65fa11a1e547a49d0453d3',
    messagingSenderId: '713866295722',
    projectId: 'my-myntra-clone',
    authDomain: 'my-myntra-clone.firebaseapp.com',
    storageBucket: 'my-myntra-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOaqhPKcN7CD5bnP7RLKbUNylxBFUpJDo',
    appId: '1:713866295722:android:0e8ea55d132776fe0453d3',
    messagingSenderId: '713866295722',
    projectId: 'my-myntra-clone',
    storageBucket: 'my-myntra-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy9Ak6WvtdYFVtbovOoM7y6prQC-PqaQY',
    appId: '1:713866295722:ios:66085e3f8cc349810453d3',
    messagingSenderId: '713866295722',
    projectId: 'my-myntra-clone',
    storageBucket: 'my-myntra-clone.appspot.com',
    iosClientId: '713866295722-67ajiecsld3q571n7b6vh7k8bfcagl01.apps.googleusercontent.com',
    iosBundleId: 'com.example.myntraClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy9Ak6WvtdYFVtbovOoM7y6prQC-PqaQY',
    appId: '1:713866295722:ios:66085e3f8cc349810453d3',
    messagingSenderId: '713866295722',
    projectId: 'my-myntra-clone',
    storageBucket: 'my-myntra-clone.appspot.com',
    iosClientId: '713866295722-67ajiecsld3q571n7b6vh7k8bfcagl01.apps.googleusercontent.com',
    iosBundleId: 'com.example.myntraClone',
  );
}
